### ISSUE TITLE
CARTS.SHA hash numbers are not match

### ISSUE THREAD

**Issue by archtaurus** [Abdess/retroarch_system#1]
| [CARTS.SHA] |  33152 | 74b0f217fa0e2b8bb5a2f8e2ecc69da3 | ❌ |

md5sum bios/CARTS.SHA 
54e28aa45f5e3f0d471dac5bcaad31ac  bios/CARTS.SHA

**Comment by archtaurus** [comment]
and many crc values are not match...

**Comment by archtaurus** [comment]
Change end of line from LF to CRLF fix it.

**Comment by Abdess** [comment]
Hi @archtaurus !
Thank you, I'm going to fix that. I'll also update other branches ASAP. :)
