### ISSUE TITLE
Game Boy BIOS is not named correctly

### ISSUE THREAD

**Issue by Dantasstic** [Abdess/retroarch_system#10]
The Game Boy BIOS should be named "gb_bios.bin" and not "gb_boot.bin". 

Once the file is renamed, it is detected by RetroArch and works fine.

**Comment by playday3008** [comment]
> The Game Boy BIOS should be named "gb_bios.bin" and not "gb_boot.bin".
> 
> Once the file is renamed, it is detected by RetroArch and works fine.

https://github.com/libretro/libretro-database/blob/658a2c2977424f656ecdb3bc6c2f12503e68c68b/dat/System.dat#L146

**Comment by Dantasstic** [comment]
![image](https://user-images.githubusercontent.com/48727187/142729503-ec8818be-0821-4cbd-8ef0-60ec576ac9a1.png)

**Comment by Dantasstic** [comment]
https://docs.libretro.com/library/gambatte/

**Comment by Abdess** [comment]
Thank you very much! Indeed, after taking a look here: https://github.com/libretro/libretro-core-info/tree/master

gb_boot.bin is not mentioned at all while gb_bios.bin is mentioned for gambatte, mgba and vbam. 👍

**Comment by Abdess** [comment]
> https://github.com/libretro/libretro-database/blob/658a2c2977424f656ecdb3bc6c2f12503e68c68b/dat/System.dat#L146

BIOS name is also fixed in System.dat now : https://github.com/libretro/libretro-database/commit/8d5adeff9e15248bbca0ed456c7556f7bdf04c36#diff-4c5a63267a1a6bffbd007cae6c6dd852aa2932de3191e66bd664b795c5723892
