### ISSUE TITLE
different MD5 from Lakka documentation 

### ISSUE THREAD

**Issue by Cibomatto2002** [Abdess/retroarch_system#11]
i'm not sure if Lakka MD5 checksums are bad but it's MD5 0754f903b52e3b3342202bdafb13efa5 for syscard3.pce (NEC - PC Engine - TurboGrafx 16)  saturn_bios.bin MD5 f273555d7d91e8a5a6bfd9bcf066331c (Sega - Saturn (Yabause)
 scph5502.bin (Sony - PlayStation) MD5 32736f17079d0b2b7024407c39bd3050

I found some more but I will wait to see what you guys have to say 

https://www.lakka.tv/doc/BIOSes/

**Comment by Abdess** [comment]
Very interesting.

It seems that there is a conflict between this [repository](https://github.com/libretro/libretro-super/tree/master/dist/info) and this [repository](https://github.com/libretro/libretro-database/blob/master/dat/System.dat).

It is quite similar to this issue: https://github.com/Abdess/retroarch_system/issues/10

To solve this conflict I think we'll have to report this issue to the RetroArch team.

In the meantime, to get the right hashes I suggest you to play with these 2 repos:
- https://github.com/Abdess/retroarch_system/tree/RetroArch
- https://github.com/Abdess/retroarch_system/tree/libretro

**Comment by Cibomatto2002** [comment]
Ok thank you.
