### ISSUE TITLE
Add PSXONPSP660.bin to 351ELEC release

### ISSUE THREAD

**Issue by kleingeld1** [Abdess/retroarch_system#14]
351ELEC uses PCSX ReARMed which supports PSXONPSP660.bin. As this is supposed to provide better emulation performance, I recommend adding it to the release.

**Comment by lattedesu** [comment]
Heya @kleingeld1 ,  how did you enable  PSXONPSP660.bin on 351ELEC? I simply added the file to BIOS folder and the core simply would not use it. I had tried on Tekken 3.

**Comment by kleingeld1** [comment]
I just put it in roms/bios. Maybe try changing the name to all upper or all lower case, I don't remember which was right. PCSX ReARMed should then take that BIOS according to its internal priority as described here: https://docs.libretro.com/library/pcsx_rearmed/

**Comment by lattedesu** [comment]
Thanks, just installed the BIOS, uppercase name, lowercase filename, just like you posted, and apparently it works on 351ELEC, however the information menu currently just does not show it.

I can confirm the core uses it by the boot animation, which the PSP logo misses the bottom region text. This was the step I had been struggled with.

Also another 👍 , please add this to the release download files. There's no reason not to.

**Comment by kleingeld1** [comment]
I had the same issue confirming that it's really loaded. You need to activate logging to do so, see here: https://www.reddit.com/r/RetroArch/comments/rr948t/check_which_bios_is_used_by_core_psx/

**Comment by Abdess** [comment]
It's integrated in the new pack, thanks! :)
