### ISSUE TITLE
Release Recalbox 8.0.0

### ISSUE THREAD

**Issue by sharkyiwc** [Abdess/retroarch_system#15]
Hello,

Thanks for your work, it was my starting point for version 8.

I don't know how to collaborate on this project. I didn't want to recreate a new fork.
That would be a shame!
I couldn't find any other way to inform you

Here is a 7z which contains the delta of the bios of a recalbox 8.0.0
https://1drv.ms/u/s!AtJokZih-mFshLYF-EzD0Fn4k7_XVA?e=BuOr0I

Here is the MISSING BIOS REPORT of my RPI4

SYSTEM: Playstation 2
---------------------------------------------

  MISSING REQUIRED BIOS: ps2-0230h-20080220.bin
    Path: /recalbox/share/bios/ps2/ps2-0230h-20080220.bin
    For: pcsx2
    Possible MD5 List:
      30D56E79D89FBDDF10938FA67FE3F34E

  MISSING REQUIRED BIOS: ps2-0230j-20080220.bin
    Path: /recalbox/share/bios/ps2/ps2-0230j-20080220.bin
    For: pcsx2
    Possible MD5 List:
      80AC46FA7E77B8AB4366E86948E54F83

SYSTEM: Texas Instrument TI-99/4A
---------------------------------------------

  MISSING OPTIONAL BIOS: ti-disk.ctg
    
    Notes: Disk Operating System
    For: ti99sim
    Possible MD5 List:
      04714F43347CEFB2A051A77116344B3F

for Playstation 2, PC only : https://wiki.recalbox.com/en/emulators/consoles/playstation-2/pcsx2
These are 2 bios japan, not found
ps2-0230h-20080220.bin	SCPH-90005/SCPH-90006/SCPH-90007 (Version 5.0 02/20/08 J)	30d56e79d89fbddf10938fa67fe3f34e
ps2-0230j-20080220.bin	SCPH-90000 (Version 5.0 02/20/08 J)	80ac46fa7e77b8ab4366e86948e54f83

Concerning naomigd.zip, it is no longer shown as erroneous on my site ?
Despite MD5 being 44F77476DBDE37E82E0E8BE3C858A459

For this file, I think he may have several possibilities. Anyone can create a zip with the right files. What is important is that the content is respected.
The contents of the zip must be :
epr-21576e.ic27	2,00 MiB CRC: 08c0add7 SHA1: e7c1a7673cb2ccb21748ef44105e46d1bad7266d
epr-21576g.ic27	2,00 MiB CRC: d2a1c6bf SHA1: 6d27d71aec4dfba98f66316ae74a1426d567698a
epr-21576h.ic27	2,00 MiB CRC: d4895685 SHA1: 91424d481ff99a8d3f4c45cea6d3f0eada049a6d
epr-21577e.ic27	2,00 MiB CRC: cf36e97b SHA1: b085305982e7572e58b03a9d35f17ae319c3bbc6
epr-21577g.ic27	2,00 MiB CRC: 25f64af7 SHA1: 99f9e6cc0642319bd2da492611220540add573e8
epr-21577h.ic27	2,00 MiB CRC: fdf17452 SHA1: 5f3e4b677f0046ce690a4f096b0481e5dd8bb6e6
epr-21578e.ic27	2,00 MiB CRC: 087f09a3 SHA1: 0418eb2cf9766f0b1b874a4e92528779e22c0a4a
epr-21578g.ic27	2,00 MiB CRC: 55413214 SHA1: bd2748365a9fc1821c9369aa7155d7c41c4df43e
epr-21578h.ic27	2,00 MiB CRC: 7b452946 SHA1: 8e9f153bbada24b37066dc45b64a7bf0d4f26a9b
main_eeprom.bin	128 B CRC: fea29cbb SHA1: 4099f1747aafa07db34f6e072cd9bfaa83bae10e
x76f100_eeprom.bin 132 B CRC: 3ea24b6a SHA1: 3a730ebcf56e0060fef6b1b02eb2eb7cfb7e61dc

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=naomigd

**Comment by Abdess** [comment]
Hi @sharkyiwc 

Sorry for my late reply. Thank you very much for your contribution, it is very helpful. 👍 

I just updated the repository based on your great report :
https://github.com/Abdess/retroarch_system/tree/Recalbox
