### ISSUE TITLE
NeoGeo bios files missing with 351ELEC - 20211122 Pineapple Forest

### ISSUE THREAD

**Issue by maxengel** [Abdess/retroarch_system#17]
`Game Settings` > `Missing BIOS Check` returns:

```
NeoGeo
- neogeo/neogeo.zip
- Missing - MD5: -
NeoGeo CD
- neogeo/neogeo.zip
- Missing - MD5: -
```

copying the root level `neogeo` directory does not solve the issue.

**Comment by Abdess** [comment]
Hello @maxengel I will upload a fix you tell me if it works :)

**Comment by Abdess** [comment]
Great 😄
