### ISSUE TITLE
Some batocera 34 bios are missing, or present with wrong md5sum/name.

### ISSUE THREAD

**Issue by arpaterson** [Abdess/retroarch_system#19]
How can I help to polish this up?

The following are reported as missing/wrong bios on my pi3B+/batocera34 (2022/05/24)

apple2e.zip
apple2gs.zip
aa310.zip
dc/awbios.zip (present in bios, correct md5, needs to be in bios/dc/ )
bbc_tube_80186.zip
bbcm.zip
bbcmc.zip
bbc_bitztik1.zip
bbc_bitstik2.zip
fmtmarty.zip
fmtowns.zip
fmtownsux.zip
dc/naomi.zip (present in bios, correct md5, needs to be in bios/dc/ )
dc/naomi2.zip (present in bios, correct md5, needs to be in bios/dc/ )
neocd/neocd_f.rom
neocd/neocd_sf.rom
neocd/neocd_t.rom
neocd/neocd_st.rom
neocd/neocd_z.rom
neocd/neocd_sz.rom
neocd/front-sp1.bin
neocd/top-sp1.bin
neocd/neocd.bin
neocd/uni-bioscd.bin
zcdata.dat

**Comment by Abdess** [comment]
Thanks for your feedback :)
The repository has just been updated (https://github.com/Abdess/retroarch_system/commit/31e6b8b147619ecfbd7b228ccec4f67d7ba142bb). I'm listening if you have any suggestions for improvement.
