### ISSUE TITLE
Possible to create a set for retrobat

### ISSUE THREAD

**Issue by porterballs** [Abdess/retroarch_system#2]
Hello i have been looking around to find the correct BIOS set to match the retrobat hash but no luck, was wondering if you may incorporate that into your releases, i thought maybe the batocera set would match but no luck. thanks

**Comment by Abdess** [comment]
Hi @porterballs 

Sorry for the very late reply.

Could you tell me which bios do not have the corresponding hash please?
I'm unfortunately running out of time to check it myself.

As soon as you give me the invalid bios with the expected hash I will update as soon as possible.

**Comment by Abdess** [comment]
@porterballs 
Here is it : https://github.com/Abdess/retroarch_system/releases/download/1.9.1/Retrobat_BIOS-Pack_3.1.zip
