### ISSUE TITLE
After installing v2.3.5 - still v2.3.4 displayed

### ISSUE THREAD

**Issue by pisaura** [Abdess/retroarch_system#27]
I've installed the new release Version 2.3.5. On the Case Panel you can see this correct version. But on the Administrator Panel Version 2.3.4 is still displayed as well as in the Settings --> About. After clicking "Check Update" the following message pops up: "New Update Available: v2.3.5".

The following docker containers are shown (docker ps):

IMAGE                          
dfirkuiper/kuiper_nginx:2.3.4  
dfirkuiper/kuiper_flask:2.3.5  
dfirkuiper/kuiper_celery:2.3.5 
dfirkuiper/kuiper_redis:2.3.5  
dfirkuiper/kuiper_mongodb:2.3.4
dfirkuiper/kuiper_es01:2.3.4

**Comment by SpiralBrad** [comment]
@pisaura Wrong repository.

**Comment by pisaura** [comment]
@SpiralBrad Sorry for that.

**Comment by pisaura** [comment]
Wrong repository. Sorry for that.
