### ISSUE TITLE
[Enhancement] Add PS2 bios files

### ISSUE THREAD

**Issue by gorshco** [Abdess/retroarch_system#3]
PS2 emulation was officially launched within RetroArch.
PS2 bios files can be added from: https://emulation.gametechwiki.com/index.php/Emulator_Files#PlayStation_2 (Hashes: https://emulation.gametechwiki.com/index.php/File_Hashes#PlayStation_2_.28PS2.29)

**Comment by Abdess** [comment]
Hello @gorshco 

Thanks for your message.

The bios of the PS2 is already integrated in the retroarch branch.

Take a look here 😉  : https://github.com/Abdess/retroarch_system/tree/RetroArch/system
![image](https://user-images.githubusercontent.com/3028866/115108336-39372180-9f70-11eb-816f-5c4eebc13f41.png)

If you notice any bios to update or correct, please, notify me, it helps me a lot. 😄

**Comment by Abdess** [comment]
Oh yeah my bad sorry I misunderstood.
I'm uploading it, wait.
You're speaking about that, right ? : https://youtu.be/-EnWeztB8wI

**Comment by Abdess** [comment]
https://github.com/Abdess/retroarch_system/commit/f411df23d479f2e751b4123062eb224a9e58a263

**Comment by gorshco** [comment]
Yep!

**Comment by Abdess** [comment]
Noice!
