### ISSUE TITLE
Build of releases

### ISSUE THREAD

**Issue by m-osmani** [Abdess/retroarch_system#4]
Hi,

thx for your work. Where can i find the code how you are creating the package for 351elec as release.

Best regards

**Comment by Abdess** [comment]
Hi @m-osmani 

To make this package, I simply used the various BIOSes available through the different branches.
Regarding the cheksum I used this file: https://github.com/351ELEC/351ELEC/blob/main/packages/351elec/sources/scripts/batocera-systems

Best Regards

**Comment by m-osmani** [comment]
Thx, the key are the branches. i didnt see them :)
