### ISSUE TITLE
unzip - missing files

### ISSUE THREAD

**Issue by iamdevnull** [Abdess/retroarch_system#5]
Hi,

this is my env:
└──╼ #unzip --help
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

If i try to extract the file https://github.com/Abdess/retroarch_system/releases/download/1.9.1/351ELEC_BIOS-Pack_20210422.zip like this:

unzip 351ELEC_BIOS-Pack_20210422.zip -d 351ELEC_BIOS-Pack_20210422/

a lot of files under 351ELEC_BIOS-Pack_20210422/bios/ are missing.

But when i open/extract the zip file with engrampa (https://github.com/mate-desktop/engrampa) then all files are present.

Any idea why unzip is behaving buggy?

Best regards

**Comment by anonymouz** [comment]
I can duplicate the problem! The "unzip" (UnZip 6.00) on my Linux desktop is NOT correctly unpacking the "351ELEC_BIOS-Pack_20210422.zip" file.

My command line "7z" (command "x") works fine! Somehow unzip is buggy -or- the used tool to create the archive is buggy...

I hope this helps someone.

**Comment by Abdess** [comment]
Yes, sorry about it. It's because I use 7zip with those parameters :
![image](https://user-images.githubusercontent.com/3028866/122929695-874f1380-d36b-11eb-8d6e-688fa438414f.png)

I will change to a compression algorithm which is compatible by default with a maximum of OS.
