### ISSUE TITLE
Missing and Incorrect Bios in Recalbox 7.2.2 RPI4

### ISSUE THREAD

**Issue by radioactiveSue** [Abdess/retroarch_system#6]
The recalbox 7.1.1 bios pack is missing md5 matching dmg_boot.bin, cgb_boot.bin, and sgb2_boot.bin.

[Here is my missing bios report text file.](https://drive.google.com/file/d/1YP9c6FXwN4Bh4JYpuNFfdPAp1WO4UBnY/view?usp=drivesdk)

**Comment by Abdess** [comment]
Hi @radioactiveSue thanks for your help, I appreciate it! I'll take a look at it over the weekend. :+1:

**Comment by Abdess** [comment]
Hi @radioactiveSue here the link :https://github.com/Abdess/retroarch_system/releases/tag/7.2.2-Reloaded
Sorry for the delay.

For the package to be perfect the file naomigd.zip should have one of these hashes:
- 288CDE03A112E7726FA8093E05D46853
- 416B5914ACB3D0B4A190A1D358C8710D
- BD9F19B4BE0692E92E272D0EB82402F7
- BE57D3744E71A3396FB8DC59830E880A

Have a nice retro gaming :)
