### ISSUE TITLE
Couple of updates for 351ELEC RG351(MP)

### ISSUE THREAD

**Issue by fl4shb1c** [Abdess/retroarch_system#9]
**Awesome work!!** Just a couple of updates

Missing files: bios/ColecoVision.rom & bios/BIOS.col
Missing folders: bios/quasi88 & bios/xmil

[bios update.zip](https://github.com/Abdess/retroarch_system/files/7428768/bios.update.zip)

**Comment by Abdess** [comment]
A month late but here is it 😄 : https://github.com/Abdess/retroarch_system/releases/tag/RetroArch-v1.9.13
